### ISSUE TITLE
blitz.gg error after update

### ISSUE THREAD

**Issue by yannickgrammont** [mmtrt/leagueoflegends#158]
Hello,

Blitz install well and launch but after he update itself there was error on launch

```
info [AutoUpdater] CHANNEL =  latest
info Copying over Blitz Dependencies from C:\users\1266401167\Local Settings\Application Data\Programs\Blitz\resources\helper 
info [2020-11-3 11:47:38] TESTING HWA C:\users\1266401167\Application Data\Blitz\hw_disable false
ERR! [2020-11-3 11:47:38] Error: internal error in Neon module: called `Result::unwrap()` on an `Err` value: SqliteFailure(Error { code: CannotOpen, extended_code: 526 }, Some("unable to open database: C:\\users\\1266401167\\Local Settings\\Application Data\\Google\\Chrome\\User Data\\Default\\Cookies"))
ERR! [2020-11-3 11:47:38]     at Object.<anonymous> (C:\users\1266401167\Local Settings\Application Data\Programs\Blitz\resources\app.asar\src\index.js:146:15)
ERR! [2020-11-3 11:47:38]     at Module._compile (internal/modules/cjs/loader.js:1152:30)
ERR! [2020-11-3 11:47:38]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10)
ERR! [2020-11-3 11:47:38]     at Module.load (internal/modules/cjs/loader.js:992:32)
ERR! [2020-11-3 11:47:38]     at Module._load (internal/modules/cjs/loader.js:885:14)
ERR! [2020-11-3 11:47:38]     at Function.f._load (electron/js2c/asar_bundle.js:5:12589)
ERR! [2020-11-3 11:47:38]     at Object.<anonymous> (electron/js2c/browser_init.js:181:3510)
ERR! [2020-11-3 11:47:38]     at Object../lib/browser/init.ts (electron/js2c/browser_init.js:181:3714)
ERR! [2020-11-3 11:47:38]     at __webpack_require__ (electron/js2c/browser_init.js:1:128)
ERR! [2020-11-3 11:47:38]     at electron/js2c/browser_init.js:1:1200
ERR! [2020-11-3 11:47:38]  BLITZ_INIT Error: internal error in Neon module: called `Result::unwrap()` on an `Err` value: SqliteFailure(Error { code: CannotOpen, extended_code: 526 }, Some("unable to open database: C:\\users\\1266401167\\Local Settings\\Application Data\\Google\\Chrome\\User Data\\Default\\Cookies"))
ERR! [2020-11-3 11:47:38]     at Object.<anonymous> (C:\users\1266401167\Local Settings\Application Data\Programs\Blitz\resources\app.asar\src\index.js:146:15)
ERR! [2020-11-3 11:47:38]     at Module._compile (internal/modules/cjs/loader.js:1152:30)
ERR! [2020-11-3 11:47:38]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10)
ERR! [2020-11-3 11:47:38]     at Module.load (internal/modules/cjs/loader.js:992:32)
ERR! [2020-11-3 11:47:38]     at Module._load (internal/modules/cjs/loader.js:885:14)
ERR! [2020-11-3 11:47:38]     at Function.f._load (electron/js2c/asar_bundle.js:5:12589)
ERR! [2020-11-3 11:47:38]     at Object.<anonymous> (electron/js2c/browser_init.js:181:3510)
ERR! [2020-11-3 11:47:38]     at Object../lib/browser/init.ts (electron/js2c/browser_init.js:181:3714)
ERR! [2020-11-3 11:47:38]     at __webpack_require__ (electron/js2c/browser_init.js:1:128)
ERR! [2020-11-3 11:47:38]     at electron/js2c/browser_init.js:1:1200
wine: Unhandled page fault on execute access to 00000000 at address 00000000 (thread 0009), starting debugger...
Unhandled exception: page fault on execute access to 0x00000000 bad address.
Assertion failed: curr_mode == stm_32bit, file cpu_i386.c, line 278
```

**Comment by yannickgrammont** [comment]
with the beta platform (snap refresh --beta wine-platform-runtime)

the error change :
#
# Fatal error in , line 0
# Version mismatch between V8 binary and snapshot.
#   V8 binary version: 7.8.279.23-electron.0
#    Snapshot version: 198-electron.0
# The snapshot consists of 171039 bytes and contains 3 context(s).
#
#
#

**Comment by mmtrt** [comment]
newer version doesn't work atm use older version.

**Comment by yannickgrammont** [comment]
ok, thanks you know how to block update ?
